export {default as Home} from "./Home"
export {default as About} from "./About"
export {default as Contact} from "./Contact"
export {default as Download} from "./Download"
export {default as LikedImg} from "./LikedImg"
export {default as Nopage} from "./Nopage"
export {default as ImageInfo} from "./ImageInfo"